# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `erubi` gem.
# Please instead update this file by running `bin/tapioca gem erubi`.


# source://erubi//lib/erubi.rb#3
module Erubi
  private

  def h(_arg0); end

  class << self
    def h(_arg0); end
  end
end

# source://erubi//lib/erubi.rb#51
class Erubi::Engine
  # source://erubi//lib/erubi.rb#91
  def initialize(input, properties = T.unsafe(nil)); end

  # source://erubi//lib/erubi.rb#62
  def bufvar; end

  # source://erubi//lib/erubi.rb#59
  def filename; end

  # source://erubi//lib/erubi.rb#56
  def src; end

  private

  # source://erubi//lib/erubi.rb#223
  def add_code(code); end

  # source://erubi//lib/erubi.rb#232
  def add_expression(indicator, code); end

  # source://erubi//lib/erubi.rb#241
  def add_expression_result(code); end

  # source://erubi//lib/erubi.rb#246
  def add_expression_result_escaped(code); end

  # source://erubi//lib/erubi.rb#252
  def add_postamble(postamble); end

  # source://erubi//lib/erubi.rb#210
  def add_text(text); end

  # source://erubi//lib/erubi.rb#258
  def handle(indicator, code, tailch, rspace, lspace); end

  # source://erubi//lib/erubi.rb#286
  def terminate_expression; end

  # source://erubi//lib/erubi.rb#268
  def with_buffer; end
end

# source://erubi//lib/erubi.rb#53
Erubi::Engine::DEFAULT_REGEXP = T.let(T.unsafe(nil), Regexp)

# source://erubi//lib/erubi.rb#17
Erubi::FREEZE_TEMPLATE_LITERALS = T.let(T.unsafe(nil), TrueClass)

# source://erubi//lib/erubi.rb#15
Erubi::MATCH_METHOD = T.let(T.unsafe(nil), Symbol)

# source://erubi//lib/erubi.rb#8
Erubi::RANGE_FIRST = T.let(T.unsafe(nil), Integer)

# source://erubi//lib/erubi.rb#9
Erubi::RANGE_LAST = T.let(T.unsafe(nil), Integer)

# source://erubi//lib/erubi.rb#16
Erubi::SKIP_DEFINED_FOR_INSTANCE_VARIABLE = T.let(T.unsafe(nil), TrueClass)

# source://erubi//lib/erubi.rb#4
Erubi::VERSION = T.let(T.unsafe(nil), String)
