# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `json` gem.
# Please instead update this file by running `bin/tapioca gem json`.


# source://json//lib/json/common.rb#867
class Class < ::Module
  # source://json//lib/json/common.rb#872
  def json_creatable?; end
end

# source://json//lib/json/version.rb#3
module JSON
  private

  # source://json//lib/json/common.rb#771
  def dump(obj, anIO = T.unsafe(nil), limit = T.unsafe(nil), kwargs = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#312
  def fast_generate(obj, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#312
  def fast_unparse(obj, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#284
  def generate(obj, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#690
  def load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#233
  def load_file(filespec, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#244
  def load_file!(filespec, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#815
  def merge_dump_options(opts, strict: T.unsafe(nil)); end

  # source://json//lib/json/common.rb#203
  def parse(source, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#218
  def parse!(source, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#357
  def pretty_generate(obj, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#357
  def pretty_unparse(obj, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#716
  def recurse_proc(result, &proc); end

  # source://json//lib/json/common.rb#690
  def restore(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#284
  def unparse(obj, opts = T.unsafe(nil)); end

  # source://json//lib/json/common.rb#536
  def unsafe_load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

  class << self
    # source://json//lib/json/common.rb#22
    def [](object, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#79
    def create_fast_state; end

    # source://json//lib/json/common.rb#114
    def create_id; end

    # source://json//lib/json/common.rb#108
    def create_id=(new_value); end

    # source://json//lib/json/common.rb#89
    def create_pretty_state; end

    # source://json//lib/json/common.rb#49
    def deep_const_get(path); end

    # source://json//lib/json/common.rb#771
    def dump(obj, anIO = T.unsafe(nil), limit = T.unsafe(nil), kwargs = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#737
    def dump_default_options; end

    # source://json//lib/json/common.rb#737
    def dump_default_options=(_arg0); end

    # source://json//lib/json/common.rb#312
    def fast_generate(obj, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#312
    def fast_unparse(obj, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#284
    def generate(obj, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#99
    def generator; end

    # source://json//lib/json/common.rb#56
    def generator=(generator); end

    # source://json//lib/json/common.rb#811
    def iconv(to, from, string); end

    # source://json//lib/json/common.rb#690
    def load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#401
    def load_default_options; end

    # source://json//lib/json/common.rb#401
    def load_default_options=(_arg0); end

    # source://json//lib/json/common.rb#233
    def load_file(filespec, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#244
    def load_file!(filespec, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#203
    def parse(source, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#218
    def parse!(source, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#36
    def parser; end

    # source://json//lib/json/common.rb#39
    def parser=(parser); end

    # source://json//lib/json/common.rb#357
    def pretty_generate(obj, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#357
    def pretty_unparse(obj, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#716
    def recurse_proc(result, &proc); end

    # source://json//lib/json/common.rb#690
    def restore(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#102
    def state; end

    # source://json//lib/json/common.rb#102
    def state=(_arg0); end

    # source://json//lib/json/common.rb#284
    def unparse(obj, opts = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#536
    def unsafe_load(source, proc = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://json//lib/json/common.rb#387
    def unsafe_load_default_options; end

    # source://json//lib/json/common.rb#387
    def unsafe_load_default_options=(_arg0); end

    private

    # source://json//lib/json/common.rb#815
    def merge_dump_options(opts, strict: T.unsafe(nil)); end
  end
end

# source://json//lib/json/ext/generator/state.rb#6
class JSON::Ext::Generator::State
  # source://json//lib/json/ext/generator/state.rb#25
  def initialize(opts = T.unsafe(nil)); end

  # source://json//lib/json/ext/generator/state.rb#83
  def [](name); end

  # source://json//lib/json/ext/generator/state.rb#95
  def []=(name, value); end

  # source://json//lib/json/ext/generator/state.rb#35
  def configure(opts); end

  # source://json//lib/json/ext/generator/state.rb#35
  def merge(opts); end

  # source://json//lib/json/ext/generator/state.rb#54
  def to_h; end

  # source://json//lib/json/ext/generator/state.rb#54
  def to_hash; end
end

# source://json//lib/json/generic_object.rb#9
class JSON::GenericObject < ::OpenStruct
  # source://json//lib/json/generic_object.rb#67
  def as_json(*_arg0); end

  # source://json//lib/json/generic_object.rb#51
  def to_hash; end

  # source://json//lib/json/generic_object.rb#71
  def to_json(*a); end

  # source://json//lib/json/generic_object.rb#63
  def |(other); end

  class << self
    # source://json//lib/json/generic_object.rb#45
    def dump(obj, *args); end

    # source://json//lib/json/generic_object.rb#25
    def from_hash(object); end

    # source://json//lib/json/generic_object.rb#17
    def json_creatable=(_arg0); end

    # source://json//lib/json/generic_object.rb#13
    def json_creatable?; end

    # source://json//lib/json/generic_object.rb#19
    def json_create(data); end

    # source://json//lib/json/generic_object.rb#40
    def load(source, proc = T.unsafe(nil), opts = T.unsafe(nil)); end
  end
end

# source://json//lib/json/common.rb#125
class JSON::JSONError < ::StandardError
  class << self
    # source://json//lib/json/common.rb#126
    def wrap(exception); end
  end
end

# source://json//lib/json/common.rb#7
JSON::NOT_SET = T.let(T.unsafe(nil), Object)

# source://json//lib/json/common.rb#42
JSON::Parser = JSON::Ext::Parser

# source://json//lib/json/common.rb#71
JSON::State = JSON::Ext::Generator::State

# source://json//lib/json/common.rb#147
JSON::UnparserError = JSON::GeneratorError

# source://json//lib/json/common.rb#825
module Kernel
  private

  # source://json//lib/json/common.rb#852
  def JSON(object, *args); end

  # source://json//lib/json/common.rb#830
  def j(*objs); end

  # source://json//lib/json/common.rb#839
  def jj(*objs); end
end
