# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `net-smtp` gem.
# Please instead update this file by running `bin/tapioca gem net-smtp`.


# source://net-smtp//lib/net/smtp.rb#194
class Net::SMTP < ::Net::Protocol
  # source://net-smtp//lib/net/smtp.rb#248
  def initialize(address, port = T.unsafe(nil), tls: T.unsafe(nil), starttls: T.unsafe(nil), tls_verify: T.unsafe(nil), tls_hostname: T.unsafe(nil), ssl_context_params: T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#414
  def address; end

  # source://net-smtp//lib/net/smtp.rb#329
  def auth_capable?(type); end

  # source://net-smtp//lib/net/smtp.rb#872
  def authenticate(user, secret, authtype = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#307
  def capabilities; end

  # source://net-smtp//lib/net/smtp.rb#301
  def capable?(key); end

  # source://net-smtp//lib/net/smtp.rb#337
  def capable_auth_types; end

  # source://net-smtp//lib/net/smtp.rb#323
  def capable_cram_md5_auth?; end

  # source://net-smtp//lib/net/smtp.rb#317
  def capable_login_auth?; end

  # source://net-smtp//lib/net/smtp.rb#311
  def capable_plain_auth?; end

  # source://net-smtp//lib/net/smtp.rb#296
  def capable_starttls?; end

  # source://net-smtp//lib/net/smtp.rb#958
  def data(msgstr = T.unsafe(nil), &block); end

  # source://net-smtp//lib/net/smtp.rb#450
  def debug_output=(arg); end

  # source://net-smtp//lib/net/smtp.rb#364
  def disable_ssl; end

  # source://net-smtp//lib/net/smtp.rb#408
  def disable_starttls; end

  # source://net-smtp//lib/net/smtp.rb#364
  def disable_tls; end

  # source://net-smtp//lib/net/smtp.rb#907
  def ehlo(domain); end

  # source://net-smtp//lib/net/smtp.rb#353
  def enable_ssl(context = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#390
  def enable_starttls(context = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#399
  def enable_starttls_auto(context = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#353
  def enable_tls(context = T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#289
  def esmtp; end

  # source://net-smtp//lib/net/smtp.rb#289
  def esmtp=(_arg0); end

  # source://net-smtp//lib/net/smtp.rb#289
  def esmtp?; end

  # source://net-smtp//lib/net/smtp.rb#655
  def finish; end

  # source://net-smtp//lib/net/smtp.rb#989
  def get_response(reqline); end

  # source://net-smtp//lib/net/smtp.rb#903
  def helo(domain); end

  # source://net-smtp//lib/net/smtp.rb#278
  def inspect; end

  # source://net-smtp//lib/net/smtp.rb#912
  def mailfrom(from_addr); end

  # source://net-smtp//lib/net/smtp.rb#849
  def open_message_stream(from_addr, *to_addrs, &block); end

  # source://net-smtp//lib/net/smtp.rb#422
  def open_timeout; end

  # source://net-smtp//lib/net/smtp.rb#422
  def open_timeout=(_arg0); end

  # source://net-smtp//lib/net/smtp.rb#417
  def port; end

  # source://net-smtp//lib/net/smtp.rb#985
  def quit; end

  # source://net-smtp//lib/net/smtp.rb#930
  def rcptto(to_addr); end

  # source://net-smtp//lib/net/smtp.rb#921
  def rcptto_list(to_addrs); end

  # source://net-smtp//lib/net/smtp.rb#427
  def read_timeout; end

  # source://net-smtp//lib/net/smtp.rb#431
  def read_timeout=(sec); end

  # source://net-smtp//lib/net/smtp.rb#849
  def ready(from_addr, *to_addrs, &block); end

  # source://net-smtp//lib/net/smtp.rb#895
  def rset; end

  # source://net-smtp//lib/net/smtp.rb#794
  def send_mail(msgstr, from_addr, *to_addrs); end

  # source://net-smtp//lib/net/smtp.rb#794
  def send_message(msgstr, from_addr, *to_addrs); end

  # source://net-smtp//lib/net/smtp.rb#794
  def sendmail(msgstr, from_addr, *to_addrs); end

  # source://net-smtp//lib/net/smtp.rb#450
  def set_debug_output(arg); end

  # source://net-smtp//lib/net/smtp.rb#344
  def ssl?; end

  # source://net-smtp//lib/net/smtp.rb#275
  def ssl_context_params; end

  # source://net-smtp//lib/net/smtp.rb#275
  def ssl_context_params=(_arg0); end

  # source://net-smtp//lib/net/smtp.rb#622
  def start(*args, helo: T.unsafe(nil), user: T.unsafe(nil), secret: T.unsafe(nil), password: T.unsafe(nil), authtype: T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#553
  def started?; end

  # source://net-smtp//lib/net/smtp.rb#899
  def starttls; end

  # source://net-smtp//lib/net/smtp.rb#374
  def starttls?; end

  # source://net-smtp//lib/net/smtp.rb#379
  def starttls_always?; end

  # source://net-smtp//lib/net/smtp.rb#384
  def starttls_auto?; end

  # source://net-smtp//lib/net/smtp.rb#344
  def tls?; end

  # source://net-smtp//lib/net/smtp.rb#272
  def tls_hostname; end

  # source://net-smtp//lib/net/smtp.rb#272
  def tls_hostname=(_arg0); end

  # source://net-smtp//lib/net/smtp.rb#269
  def tls_verify; end

  # source://net-smtp//lib/net/smtp.rb#269
  def tls_verify=(_arg0); end

  private

  # source://net-smtp//lib/net/smtp.rb#748
  def any_require_smtputf8(addresses); end

  # source://net-smtp//lib/net/smtp.rb#880
  def check_auth_args(type, *args, **kwargs); end

  # source://net-smtp//lib/net/smtp.rb#1040
  def check_continue(res); end

  # source://net-smtp//lib/net/smtp.rb#1034
  def check_response(res); end

  # source://net-smtp//lib/net/smtp.rb#1024
  def critical; end

  # source://net-smtp//lib/net/smtp.rb#731
  def do_finish; end

  # source://net-smtp//lib/net/smtp.rb#719
  def do_helo(helo_domain); end

  # source://net-smtp//lib/net/smtp.rb#666
  def do_start(helo_domain, user, secret, authtype); end

  # source://net-smtp//lib/net/smtp.rb#1004
  def getok(reqline); end

  # source://net-smtp//lib/net/smtp.rb#1125
  def logging(msg); end

  # source://net-smtp//lib/net/smtp.rb#714
  def new_internet_message_io(s); end

  # source://net-smtp//lib/net/smtp.rb#1014
  def recv_response; end

  # source://net-smtp//lib/net/smtp.rb#740
  def requires_smtputf8(address); end

  # source://net-smtp//lib/net/smtp.rb#697
  def ssl_socket(socket, context); end

  # source://net-smtp//lib/net/smtp.rb#662
  def tcp_socket(address, port); end

  # source://net-smtp//lib/net/smtp.rb#701
  def tlsconnect(s, context); end

  # source://net-smtp//lib/net/smtp.rb#997
  def validate_line(line); end

  class << self
    # source://net-smtp//lib/net/smtp.rb#198
    def default_port; end

    # source://net-smtp//lib/net/smtp.rb#216
    def default_ssl_context(ssl_context_params = T.unsafe(nil)); end

    # source://net-smtp//lib/net/smtp.rb#208
    def default_ssl_port; end

    # source://net-smtp//lib/net/smtp.rb#203
    def default_submission_port; end

    # source://net-smtp//lib/net/smtp.rb#208
    def default_tls_port; end

    # source://net-smtp//lib/net/smtp.rb#539
    def start(address, port = T.unsafe(nil), *args, helo: T.unsafe(nil), user: T.unsafe(nil), secret: T.unsafe(nil), password: T.unsafe(nil), authtype: T.unsafe(nil), tls: T.unsafe(nil), starttls: T.unsafe(nil), tls_verify: T.unsafe(nil), tls_hostname: T.unsafe(nil), ssl_context_params: T.unsafe(nil), &block); end
  end
end

# source://net-smtp//lib/net/smtp.rb#1130
class Net::SMTP::Address
  # source://net-smtp//lib/net/smtp.rb#1141
  def initialize(address, *args, **kw_args); end

  # source://net-smtp//lib/net/smtp.rb#1132
  def address; end

  # source://net-smtp//lib/net/smtp.rb#1134
  def parameters; end

  # source://net-smtp//lib/net/smtp.rb#1152
  def to_s; end
end

# source://net-smtp//lib/net/smtp/auth_cram_md5.rb#9
class Net::SMTP::AuthCramMD5 < ::Net::SMTP::Authenticator
  # source://net-smtp//lib/net/smtp/auth_cram_md5.rb#12
  def auth(user, secret); end

  # source://net-smtp//lib/net/smtp/auth_cram_md5.rb#22
  def cram_md5_response(secret, challenge); end

  # source://net-smtp//lib/net/smtp/auth_cram_md5.rb#29
  def cram_secret(secret, mask); end

  # source://net-smtp//lib/net/smtp/auth_cram_md5.rb#38
  def digest_class; end
end

# source://net-smtp//lib/net/smtp/auth_cram_md5.rb#27
Net::SMTP::AuthCramMD5::CRAM_BUFSIZE = T.let(T.unsafe(nil), Integer)

# source://net-smtp//lib/net/smtp/auth_cram_md5.rb#18
Net::SMTP::AuthCramMD5::IMASK = T.let(T.unsafe(nil), Integer)

# source://net-smtp//lib/net/smtp/auth_cram_md5.rb#19
Net::SMTP::AuthCramMD5::OMASK = T.let(T.unsafe(nil), Integer)

# source://net-smtp//lib/net/smtp/auth_login.rb#2
class Net::SMTP::AuthLogin < ::Net::SMTP::Authenticator
  # source://net-smtp//lib/net/smtp/auth_login.rb#5
  def auth(user, secret); end
end

# source://net-smtp//lib/net/smtp/auth_plain.rb#2
class Net::SMTP::AuthPlain < ::Net::SMTP::Authenticator
  # source://net-smtp//lib/net/smtp/auth_plain.rb#5
  def auth(user, secret); end
end

# source://net-smtp//lib/net/smtp/auth_xoauth2.rb#2
class Net::SMTP::AuthXoauth2 < ::Net::SMTP::Authenticator
  # source://net-smtp//lib/net/smtp/auth_xoauth2.rb#5
  def auth(user, secret); end

  private

  # source://net-smtp//lib/net/smtp/auth_xoauth2.rb#13
  def xoauth2_string(user, secret); end
end

# source://net-smtp//lib/net/smtp/authenticator.rb#3
class Net::SMTP::Authenticator
  # source://net-smtp//lib/net/smtp/authenticator.rb#29
  def initialize(smtp); end

  # source://net-smtp//lib/net/smtp/authenticator.rb#51
  def base64_encode(str); end

  # source://net-smtp//lib/net/smtp/authenticator.rb#35
  def continue(arg); end

  # source://net-smtp//lib/net/smtp/authenticator.rb#43
  def finish(arg); end

  # source://net-smtp//lib/net/smtp/authenticator.rb#27
  def smtp; end

  class << self
    # source://net-smtp//lib/net/smtp/authenticator.rb#13
    def auth_class(type); end

    # source://net-smtp//lib/net/smtp/authenticator.rb#4
    def auth_classes; end

    # source://net-smtp//lib/net/smtp/authenticator.rb#8
    def auth_type(type); end

    # source://net-smtp//lib/net/smtp/authenticator.rb#18
    def check_args(user_arg = T.unsafe(nil), secret_arg = T.unsafe(nil), *_arg2, **_arg3); end
  end
end

# source://net-smtp//lib/net/smtp.rb#1050
class Net::SMTP::Response
  # source://net-smtp//lib/net/smtp.rb#1059
  def initialize(status, string); end

  # source://net-smtp//lib/net/smtp.rb#1102
  def capabilities; end

  # source://net-smtp//lib/net/smtp.rb#1083
  def continue?; end

  # source://net-smtp//lib/net/smtp.rb#1094
  def cram_md5_challenge; end

  # source://net-smtp//lib/net/smtp.rb#1114
  def exception_class; end

  # source://net-smtp//lib/net/smtp.rb#1088
  def message; end

  # source://net-smtp//lib/net/smtp.rb#1065
  def status; end

  # source://net-smtp//lib/net/smtp.rb#1071
  def status_type_char; end

  # source://net-smtp//lib/net/smtp.rb#1068
  def string; end

  # source://net-smtp//lib/net/smtp.rb#1077
  def success?; end

  class << self
    # source://net-smtp//lib/net/smtp.rb#1053
    def parse(str); end
  end
end

# source://net-smtp//lib/net/smtp.rb#195
Net::SMTP::VERSION = T.let(T.unsafe(nil), String)

# source://net-smtp//lib/net/smtp.rb#49
class Net::SMTPAuthenticationError < ::Net::ProtoAuthError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#27
module Net::SMTPError
  # source://net-smtp//lib/net/smtp.rb#33
  def initialize(response, message: T.unsafe(nil)); end

  # source://net-smtp//lib/net/smtp.rb#43
  def message; end

  # source://net-smtp//lib/net/smtp.rb#31
  def response; end
end

# source://net-smtp//lib/net/smtp.rb#64
class Net::SMTPFatalError < ::Net::ProtoFatalError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#54
class Net::SMTPServerBusy < ::Net::ProtoServerError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#1158
Net::SMTPSession = Net::SMTP

# source://net-smtp//lib/net/smtp.rb#59
class Net::SMTPSyntaxError < ::Net::ProtoSyntaxError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#69
class Net::SMTPUnknownError < ::Net::ProtoUnknownError
  include ::Net::SMTPError
end

# source://net-smtp//lib/net/smtp.rb#74
class Net::SMTPUnsupportedCommand < ::Net::ProtocolError
  include ::Net::SMTPError
end
