# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `psych` gem.
# Please instead update this file by running `bin/tapioca gem psych`.


class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  # source://psych//psych/core_ext.rb#12
  def to_yaml(options = T.unsafe(nil)); end

  class << self
    # source://psych//psych/core_ext.rb#3
    def yaml_tag(url); end
  end
end

module Psych
  class << self
    # source://psych//psych.rb#682
    def add_builtin_type(type_tag, &block); end

    # source://psych//psych.rb#676
    def add_domain_type(domain, type_tag, &block); end

    # source://psych//psych.rb#692
    def add_tag(tag, klass); end

    # source://psych//psych.rb#708
    def config; end

    # source://psych//psych.rb#720
    def domain_types; end

    # source://psych//psych.rb#732
    def domain_types=(value); end

    # source://psych//psych.rb#505
    def dump(o, io = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://psych//psych.rb#595
    def dump_stream(*objects); end

    # source://psych//psych.rb#716
    def dump_tags; end

    # source://psych//psych.rb#728
    def dump_tags=(value); end

    # source://psych//psych.rb#368
    def load(yaml, permitted_classes: T.unsafe(nil), permitted_symbols: T.unsafe(nil), aliases: T.unsafe(nil), filename: T.unsafe(nil), fallback: T.unsafe(nil), symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil)); end

    # source://psych//psych.rb#669
    def load_file(filename, **kwargs); end

    # source://psych//psych.rb#626
    def load_stream(yaml, filename: T.unsafe(nil), fallback: T.unsafe(nil), **kwargs); end

    # source://psych//psych.rb#712
    def load_tags; end

    # source://psych//psych.rb#724
    def load_tags=(value); end

    # source://psych//psych.rb#398
    def parse(yaml, filename: T.unsafe(nil)); end

    # source://psych//psych.rb#410
    def parse_file(filename, fallback: T.unsafe(nil)); end

    # source://psych//psych.rb#452
    def parse_stream(yaml, filename: T.unsafe(nil), &block); end

    # source://psych//psych.rb#419
    def parser; end

    # source://psych//psych.rb#688
    def remove_type(type_tag); end

    # source://psych//psych.rb#578
    def safe_dump(o, io = T.unsafe(nil), options = T.unsafe(nil)); end

    # source://psych//psych.rb#322
    def safe_load(yaml, permitted_classes: T.unsafe(nil), permitted_symbols: T.unsafe(nil), aliases: T.unsafe(nil), filename: T.unsafe(nil), fallback: T.unsafe(nil), symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil)); end

    # source://psych//psych.rb#658
    def safe_load_file(filename, **kwargs); end

    # source://psych//psych.rb#605
    def to_json(object); end

    # source://psych//psych.rb#271
    def unsafe_load(yaml, filename: T.unsafe(nil), fallback: T.unsafe(nil), symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil)); end

    # source://psych//psych.rb#647
    def unsafe_load_file(filename, **kwargs); end
  end
end

class Psych::AliasesNotEnabled < ::Psych::BadAlias
  # source://psych//psych/exception.rb#11
  def initialize; end
end

class Psych::AnchorNotDefined < ::Psych::BadAlias
  # source://psych//psych/exception.rb#18
  def initialize(anchor_name); end
end

class Psych::ClassLoader
  # source://psych//psych/class_loader.rb#21
  def initialize; end

  # source://psych//psych/class_loader.rb#39
  def big_decimal; end

  # source://psych//psych/class_loader.rb#39
  def complex; end

  # source://psych//psych/class_loader.rb#39
  def date; end

  # source://psych//psych/class_loader.rb#39
  def date_time; end

  # source://psych//psych/class_loader.rb#39
  def exception; end

  # source://psych//psych/class_loader.rb#25
  def load(klassname); end

  # source://psych//psych/class_loader.rb#39
  def object; end

  # source://psych//psych/class_loader.rb#39
  def psych_omap; end

  # source://psych//psych/class_loader.rb#39
  def psych_set; end

  # source://psych//psych/class_loader.rb#39
  def range; end

  # source://psych//psych/class_loader.rb#39
  def rational; end

  # source://psych//psych/class_loader.rb#39
  def regexp; end

  # source://psych//psych/class_loader.rb#39
  def struct; end

  # source://psych//psych/class_loader.rb#39
  def symbol; end

  # source://psych//psych/class_loader.rb#31
  def symbolize(sym); end

  private

  # source://psych//psych/class_loader.rb#47
  def find(klassname); end

  # source://psych//psych/class_loader.rb#51
  def resolve(klassname); end
end

class Psych::ClassLoader::Restricted < ::Psych::ClassLoader
  # source://psych//psych/class_loader.rb#77
  def initialize(classes, symbols); end

  # source://psych//psych/class_loader.rb#83
  def symbolize(sym); end

  private

  # source://psych//psych/class_loader.rb#95
  def find(klassname); end
end

class Psych::Coder
  # source://psych//psych/coder.rb#13
  def initialize(tag); end

  # source://psych//psych/coder.rb#84
  def [](k); end

  # source://psych//psych/coder.rb#78
  def []=(k, v); end

  # source://psych//psych/coder.rb#78
  def add(k, v); end

  # source://psych//psych/coder.rb#10
  def implicit; end

  # source://psych//psych/coder.rb#10
  def implicit=(_arg0); end

  # source://psych//psych/coder.rb#34
  def map(tag = T.unsafe(nil), style = T.unsafe(nil)); end

  # source://psych//psych/coder.rb#73
  def map=(map); end

  # source://psych//psych/coder.rb#10
  def object; end

  # source://psych//psych/coder.rb#10
  def object=(_arg0); end

  # source://psych//psych/coder.rb#54
  def represent_map(tag, map); end

  # source://psych//psych/coder.rb#60
  def represent_object(tag, obj); end

  # source://psych//psych/coder.rb#42
  def represent_scalar(tag, value); end

  # source://psych//psych/coder.rb#48
  def represent_seq(tag, list); end

  # source://psych//psych/coder.rb#24
  def scalar(*args); end

  # source://psych//psych/coder.rb#67
  def scalar=(value); end

  # source://psych//psych/coder.rb#11
  def seq; end

  # source://psych//psych/coder.rb#90
  def seq=(list); end

  # source://psych//psych/coder.rb#10
  def style; end

  # source://psych//psych/coder.rb#10
  def style=(_arg0); end

  # source://psych//psych/coder.rb#10
  def tag; end

  # source://psych//psych/coder.rb#10
  def tag=(_arg0); end

  # source://psych//psych/coder.rb#11
  def type; end
end

class Psych::DisallowedClass < ::Psych::Exception
  # source://psych//psych/exception.rb#24
  def initialize(action, klass_name); end
end

class Psych::Handler
  # source://psych//psych/handler.rb#110
  def alias(anchor); end

  # source://psych//psych/handler.rb#236
  def empty; end

  # source://psych//psych/handler.rb#93
  def end_document(implicit); end

  # source://psych//psych/handler.rb#230
  def end_mapping; end

  # source://psych//psych/handler.rb#191
  def end_sequence; end

  # source://psych//psych/handler.rb#241
  def end_stream; end

  # source://psych//psych/handler.rb#246
  def event_location(start_line, start_column, end_line, end_column); end

  # source://psych//psych/handler.rb#150
  def scalar(value, anchor, tag, plain, quoted, style); end

  # source://psych//psych/handler.rb#72
  def start_document(version, tag_directives, implicit); end

  # source://psych//psych/handler.rb#225
  def start_mapping(anchor, tag, implicit, style); end

  # source://psych//psych/handler.rb#186
  def start_sequence(anchor, tag, implicit, style); end

  # source://psych//psych/handler.rb#47
  def start_stream(encoding); end

  # source://psych//psych/handler.rb#251
  def streaming?; end
end

class Psych::Handler::DumperOptions
  # source://psych//psych/handler.rb#19
  def initialize; end

  # source://psych//psych/handler.rb#17
  def canonical; end

  # source://psych//psych/handler.rb#17
  def canonical=(_arg0); end

  # source://psych//psych/handler.rb#17
  def indentation; end

  # source://psych//psych/handler.rb#17
  def indentation=(_arg0); end

  # source://psych//psych/handler.rb#17
  def line_width; end

  # source://psych//psych/handler.rb#17
  def line_width=(_arg0); end
end

class Psych::JSON::Stream < ::Psych::Visitors::JSONTree
  include ::Psych::Streaming
  extend ::Psych::Streaming::ClassMethods
end

class Psych::Parser
  # source://psych//psych/parser.rb#47
  def initialize(handler = T.unsafe(nil)); end

  # source://psych//psych/parser.rb#41
  def external_encoding=(_arg0); end

  # source://psych//psych/parser.rb#38
  def handler; end

  # source://psych//psych/parser.rb#38
  def handler=(_arg0); end

  # source://psych//psych/parser.rb#61
  def parse(yaml, path = T.unsafe(nil)); end
end

class Psych::ScalarScanner
  # source://psych//psych/scalar_scanner.rb#30
  def initialize(class_loader, strict_integer: T.unsafe(nil)); end

  # source://psych//psych/scalar_scanner.rb#27
  def class_loader; end

  # source://psych//psych/scalar_scanner.rb#109
  def parse_int(string); end

  # source://psych//psych/scalar_scanner.rb#115
  def parse_time(string); end

  # source://psych//psych/scalar_scanner.rb#37
  def tokenize(string); end
end

# source://psych//psych/scalar_scanner.rb#22
Psych::ScalarScanner::INTEGER_LEGACY = T.let(T.unsafe(nil), Regexp)

# source://psych//psych/scalar_scanner.rb#15
Psych::ScalarScanner::INTEGER_STRICT = T.let(T.unsafe(nil), Regexp)

class Psych::Stream < ::Psych::Visitors::YAMLTree
  include ::Psych::Streaming
  extend ::Psych::Streaming::ClassMethods
end

class Psych::Stream::Emitter < ::Psych::Emitter
  # source://psych//psych/stream.rb#26
  def end_document(implicit_end = T.unsafe(nil)); end

  # source://psych//psych/stream.rb#30
  def streaming?; end
end

module Psych::Streaming
  # source://psych//psych/streaming.rb#18
  def start(encoding = T.unsafe(nil)); end

  private

  # source://psych//psych/streaming.rb#25
  def register(target, obj); end
end

module Psych::Streaming::ClassMethods
  # source://psych//psych/streaming.rb#8
  def new(io); end
end

class Psych::SyntaxError < ::Psych::Exception
  # source://psych//psych/syntax_error.rb#8
  def initialize(file, line, col, offset, problem, context); end

  # source://psych//psych/syntax_error.rb#6
  def column; end

  # source://psych//psych/syntax_error.rb#6
  def context; end

  # source://psych//psych/syntax_error.rb#6
  def file; end

  # source://psych//psych/syntax_error.rb#6
  def line; end

  # source://psych//psych/syntax_error.rb#6
  def offset; end

  # source://psych//psych/syntax_error.rb#6
  def problem; end
end

class Psych::TreeBuilder < ::Psych::Handler
  # source://psych//psych/tree_builder.rb#22
  def initialize; end

  # source://psych//psych/tree_builder.rb#103
  def alias(anchor); end

  # source://psych//psych/tree_builder.rb#77
  def end_document(implicit_end = T.unsafe(nil)); end

  # source://psych//psych/tree_builder.rb#52
  def end_mapping; end

  # source://psych//psych/tree_builder.rb#52
  def end_sequence; end

  # source://psych//psych/tree_builder.rb#90
  def end_stream; end

  # source://psych//psych/tree_builder.rb#33
  def event_location(start_line, start_column, end_line, end_column); end

  # source://psych//psych/tree_builder.rb#19
  def root; end

  # source://psych//psych/tree_builder.rb#96
  def scalar(value, anchor, tag, plain, quoted, style); end

  # source://psych//psych/tree_builder.rb#65
  def start_document(version, tag_directives, implicit); end

  # source://psych//psych/tree_builder.rb#45
  def start_mapping(anchor, tag, implicit, style); end

  # source://psych//psych/tree_builder.rb#45
  def start_sequence(anchor, tag, implicit, style); end

  # source://psych//psych/tree_builder.rb#84
  def start_stream(encoding); end

  private

  # source://psych//psych/tree_builder.rb#116
  def pop; end

  # source://psych//psych/tree_builder.rb#111
  def push(value); end

  # source://psych//psych/tree_builder.rb#132
  def set_end_location(node); end

  # source://psych//psych/tree_builder.rb#122
  def set_location(node); end

  # source://psych//psych/tree_builder.rb#127
  def set_start_location(node); end
end

# source://psych//psych/versions.rb#5
Psych::VERSION = T.let(T.unsafe(nil), String)

class Psych::Visitors::DepthFirst < ::Psych::Visitors::Visitor
  # source://psych//psych/visitors/depth_first.rb#5
  def initialize(block); end

  private

  # source://psych//psych/visitors/depth_first.rb#11
  def nary(o); end

  # source://psych//psych/visitors/depth_first.rb#20
  def terminal(o); end

  # source://psych//psych/visitors/depth_first.rb#20
  def visit_Psych_Nodes_Alias(o); end

  # source://psych//psych/visitors/depth_first.rb#11
  def visit_Psych_Nodes_Document(o); end

  # source://psych//psych/visitors/depth_first.rb#11
  def visit_Psych_Nodes_Mapping(o); end

  # source://psych//psych/visitors/depth_first.rb#20
  def visit_Psych_Nodes_Scalar(o); end

  # source://psych//psych/visitors/depth_first.rb#11
  def visit_Psych_Nodes_Sequence(o); end

  # source://psych//psych/visitors/depth_first.rb#11
  def visit_Psych_Nodes_Stream(o); end
end

class Psych::Visitors::RestrictedYAMLTree < ::Psych::Visitors::YAMLTree
  # source://psych//psych/visitors/yaml_tree.rb#552
  def initialize(emitter, ss, options); end

  # source://psych//psych/visitors/yaml_tree.rb#565
  def accept(target); end

  # source://psych//psych/visitors/yaml_tree.rb#577
  def visit_Symbol(sym); end
end

# source://psych//psych/visitors/yaml_tree.rb#541
Psych::Visitors::RestrictedYAMLTree::DEFAULT_PERMITTED_CLASSES = T.let(T.unsafe(nil), Hash)

class Psych::Visitors::ToRuby < ::Psych::Visitors::Visitor
  # source://psych//psych/visitors/to_ruby.rb#23
  def initialize(ss, class_loader, symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil)); end

  # source://psych//psych/visitors/to_ruby.rb#34
  def accept(target); end

  # source://psych//psych/visitors/to_ruby.rb#21
  def class_loader; end

  # source://psych//psych/visitors/to_ruby.rb#327
  def visit_Psych_Nodes_Alias(o); end

  # source://psych//psych/visitors/to_ruby.rb#319
  def visit_Psych_Nodes_Document(o); end

  # source://psych//psych/visitors/to_ruby.rb#165
  def visit_Psych_Nodes_Mapping(o); end

  # source://psych//psych/visitors/to_ruby.rb#129
  def visit_Psych_Nodes_Scalar(o); end

  # source://psych//psych/visitors/to_ruby.rb#133
  def visit_Psych_Nodes_Sequence(o); end

  # source://psych//psych/visitors/to_ruby.rb#323
  def visit_Psych_Nodes_Stream(o); end

  private

  # source://psych//psych/visitors/to_ruby.rb#395
  def deduplicate(key); end

  # source://psych//psych/visitors/to_ruby.rb#51
  def deserialize(o); end

  # source://psych//psych/visitors/to_ruby.rb#412
  def init_with(o, h, node); end

  # source://psych//psych/visitors/to_ruby.rb#404
  def merge_key(hash, key, val); end

  # source://psych//psych/visitors/to_ruby.rb#333
  def register(node, object); end

  # source://psych//psych/visitors/to_ruby.rb#338
  def register_empty(object); end

  # source://psych//psych/visitors/to_ruby.rb#425
  def resolve_class(klassname); end

  # source://psych//psych/visitors/to_ruby.rb#407
  def revive(klass, node); end

  # source://psych//psych/visitors/to_ruby.rb#344
  def revive_hash(hash, o, tagged = T.unsafe(nil)); end

  class << self
    # source://psych//psych/visitors/to_ruby.rb#15
    def create(symbolize_names: T.unsafe(nil), freeze: T.unsafe(nil), strict_integer: T.unsafe(nil)); end
  end
end

class Psych::Visitors::Visitor
  # source://psych//psych/visitors/visitor.rb#5
  def accept(target); end

  private

  # source://psych//psych/visitors/visitor.rb#19
  def dispatch; end

  # source://psych//psych/visitors/visitor.rb#29
  def visit(target); end

  class << self
    # source://psych//psych/visitors/visitor.rb#12
    def dispatch_cache; end
  end
end

class Psych::Visitors::YAMLTree < ::Psych::Visitors::Visitor
  # source://psych//psych/visitors/yaml_tree.rb#55
  def initialize(emitter, ss, options); end

  # source://psych//psych/visitors/yaml_tree.rb#102
  def <<(object); end

  # source://psych//psych/visitors/yaml_tree.rb#122
  def accept(target); end

  # source://psych//psych/visitors/yaml_tree.rb#91
  def finish; end

  # source://psych//psych/visitors/yaml_tree.rb#44
  def finished; end

  # source://psych//psych/visitors/yaml_tree.rb#44
  def finished?; end

  # source://psych//psych/visitors/yaml_tree.rb#102
  def push(object); end

  # source://psych//psych/visitors/yaml_tree.rb#85
  def start(encoding = T.unsafe(nil)); end

  # source://psych//psych/visitors/yaml_tree.rb#44
  def started; end

  # source://psych//psych/visitors/yaml_tree.rb#44
  def started?; end

  # source://psych//psych/visitors/yaml_tree.rb#97
  def tree; end

  # source://psych//psych/visitors/yaml_tree.rb#350
  def visit_Array(o); end

  # source://psych//psych/visitors/yaml_tree.rb#376
  def visit_BasicObject(o); end

  # source://psych//psych/visitors/yaml_tree.rb#250
  def visit_BigDecimal(o); end

  # source://psych//psych/visitors/yaml_tree.rb#313
  def visit_Class(o); end

  # source://psych//psych/visitors/yaml_tree.rb#223
  def visit_Complex(o); end

  # source://psych//psych/visitors/yaml_tree.rb#194
  def visit_Date(o); end

  # source://psych//psych/visitors/yaml_tree.rb#198
  def visit_DateTime(o); end

  # source://psych//psych/visitors/yaml_tree.rb#152
  def visit_Delegator(o); end

  # source://psych//psych/visitors/yaml_tree.rb#147
  def visit_Encoding(o); end

  # source://psych//psych/visitors/yaml_tree.rb#358
  def visit_Enumerator(o); end

  # source://psych//psych/visitors/yaml_tree.rb#182
  def visit_Exception(o); end

  # source://psych//psych/visitors/yaml_tree.rb#233
  def visit_FalseClass(o); end

  # source://psych//psych/visitors/yaml_tree.rb#239
  def visit_Float(o); end

  # source://psych//psych/visitors/yaml_tree.rb#326
  def visit_Hash(o); end

  # source://psych//psych/visitors/yaml_tree.rb#233
  def visit_Integer(o); end

  # source://psych//psych/visitors/yaml_tree.rb#308
  def visit_Module(o); end

  # source://psych//psych/visitors/yaml_tree.rb#186
  def visit_NameError(o); end

  # source://psych//psych/visitors/yaml_tree.rb#364
  def visit_NilClass(o); end

  # source://psych//psych/visitors/yaml_tree.rb#152
  def visit_Object(o); end

  # source://psych//psych/visitors/yaml_tree.rb#139
  def visit_Psych_Omap(o); end

  # source://psych//psych/visitors/yaml_tree.rb#339
  def visit_Psych_Set(o); end

  # source://psych//psych/visitors/yaml_tree.rb#318
  def visit_Range(o); end

  # source://psych//psych/visitors/yaml_tree.rb#210
  def visit_Rational(o); end

  # source://psych//psych/visitors/yaml_tree.rb#190
  def visit_Regexp(o); end

  # source://psych//psych/visitors/yaml_tree.rb#254
  def visit_String(o); end

  # source://psych//psych/visitors/yaml_tree.rb#168
  def visit_Struct(o); end

  # source://psych//psych/visitors/yaml_tree.rb#368
  def visit_Symbol(o); end

  # source://psych//psych/visitors/yaml_tree.rb#205
  def visit_Time(o); end

  # source://psych//psych/visitors/yaml_tree.rb#233
  def visit_TrueClass(o); end

  private

  # source://psych//psych/visitors/yaml_tree.rb#390
  def binary?(string); end

  # source://psych//psych/visitors/yaml_tree.rb#497
  def dump_coder(o); end

  # source://psych//psych/visitors/yaml_tree.rb#466
  def dump_exception(o, msg); end

  # source://psych//psych/visitors/yaml_tree.rb#532
  def dump_ivars(target); end

  # source://psych//psych/visitors/yaml_tree.rb#463
  def dump_list(o); end

  # source://psych//psych/visitors/yaml_tree.rb#510
  def emit_coder(c, o); end

  # source://psych//psych/visitors/yaml_tree.rb#484
  def format_time(time, utc = T.unsafe(nil)); end

  # source://psych//psych/visitors/yaml_tree.rb#492
  def register(target, yaml_obj); end

  # source://psych//psych/visitors/yaml_tree.rb#394
  def visit_array_subclass(o); end

  # source://psych//psych/visitors/yaml_tree.rb#425
  def visit_hash_subclass(o); end

  class << self
    # source://psych//psych/visitors/yaml_tree.rb#48
    def create(options = T.unsafe(nil), emitter = T.unsafe(nil)); end
  end
end

class Psych::Visitors::YAMLTree::Registrar
  # source://psych//psych/visitors/yaml_tree.rb#17
  def initialize; end

  # source://psych//psych/visitors/yaml_tree.rb#35
  def id_for(target); end

  # source://psych//psych/visitors/yaml_tree.rb#29
  def key?(target); end

  # source://psych//psych/visitors/yaml_tree.rb#39
  def node_for(target); end

  # source://psych//psych/visitors/yaml_tree.rb#24
  def register(target, node); end
end
