# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NoopJob`.
# Please instead update this file by running `bin/tapioca dsl NoopJob`.


class NoopJob
  class << self
    sig { params(block: T.nilable(T.proc.params(job: NoopJob).void)).returns(T.any(NoopJob, FalseClass)) }
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
